spring:
  application:
    name: elevideo-backend

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8081}


jwt:
  secret: ${JWT_SECRET:TTE1M0NyM3RLM3lQYXJhSldUc011eVMyZ3VyNHlMNHJnNA==}
  expiration: ${JWT_EXPIRATION:3600000}


app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
    verify-email-path: ${FRONTEND_VERIFY_EMAIL_PATH:/verify-email}
    reset-password-path: ${FRONTEND_RESET_PASSWORD_PATH:/reset-password}


resend:
  api-key: ${RESEND_APIKEY}
  from-email: ${RESEND_EMAIL}
  from-name: ${RESEND_NAME}

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.elevideo.backend: DEBUG   # o TRACE para ver todo
    org.hibernate.SQL: DEBUG      # para ver queries SQL
    org.hibernate.orm.jdbc.bind: TRACE  # par√°metros de queries


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}


web:
  cors:
    allowed-origins: ${CORS_ALLOWED:http://localhost:*}
